#!/usr/bin/env python3

#Script Name: Banner_grabber
#Purpose: Get information in a banner
#Example usage: Gather intelligence
#Expected output: Services running on target

import os

print("Hi, I'm going to help you grab a banner\n")
target = input("Please provide URL or IP address: ")
port = input("Which port would you like to use? ")

print("\nLet's use Netcat first")
# Uses netcat with a timer
os.system(f"nc -w 1 {target} {port}")

print("\nNow let's do the same but with Nmap")
# Uses nmap with all ports
os.system(f"nmap -sV {target}")

print("\nAnd let us finish it with Telnet")
#Uses telnet
os.system(f"telnet {target} {port}")