#!/usr/bin/env python3

import zipfile

wordlist = "/home/vmubuntu/wordlist/cracker.txt"
path = "/home/vmubuntu/gits/401challengess/test.zip"
destination = "/home/vmubuntu/gits/401challengess"

with open(wordlist, "rb") as content:
#Reads wordlist in binary mode
    list = content.readlines()
    #Places all content in a list
    target = zipfile.ZipFile(path)
    #Places action to unzip in a variable    
    
for element in list:
    try:
        password = element.strip()
        target.extractall(path=destination, pwd=password)
        print("\nPassword cracked: ", password.decode().strip)
        print ("Contents are extracted to ", destination)
        break
   
    except:
        print("Not password found in the wordlist")