#!/usr/bin/env python3

#Script Name: bruteforce
#Purpose: checks a file line by line
#Example usage: Iterate the file line by line, may be used to match it against a password
#Expected output: List of strings in the file
#variables: choice, path, file, lines, word, string, content

import time

def menu():
    print ("\nwhat would you like to do?\n")
    print ("1) Dictionary Iterator")
    print ("2) Password Recognizer")
    print ("3) Exit")
    choice = input()
    return choice

def action(choice):    
    if choice == "1":
        iterator()
         
    elif choice == "2":
        recognizer()
    
    elif choice == "3":
        exit()
    
    else:
        print ("\nPlease choose among the options")
        
#Iterates through every word, assigns it to a variable and prints it
def iterator():
    path = input("\nPlease provide Wordlist file path: ")
    #Passes user's provided path file path into a variable
    print("\nListing all passwords...")
    file = open(path, encoding = "ISO-8859-1")
    #Opens the file and prepares it to be encoded so it can be encode to a variable
    lines = file.readline()
    #Reads every line and place it into a variable
    
    while lines:
        lines = lines.rstrip()
        #removes empty spaces after the string
        word = lines
        print(word)
        time.sleep(1)
        #Stops for 1 second
        lines = file.readline()
        #Goes to the next line
    file.close()
    #closes the file
    
# Looks to match user's input with list in a file provided
def recognizer():
    string = input("\nPlease provide password to look for: ")
    #Requests password to look for
    path = input("\nNow file path to search for a match: ")
    #File to look through
    
    f = open(path, 'r')
    #opens the file for reading 
    file = f.readlines()
    #Reads all lines of the file at once
    file.append("EOF")
    for lines in file:
        content = lines.rstrip()
        #Empty spaces are removed from the list
        if content == string:
        #if the password inputs matches 
            print("Your password appears in the list")
            break
        elif content == "EOF" and content != string:
            print("Your password is not in the list")
        else:
        #It is needed so the loop doesn't keep printing the response
            continue
    f.close()
                           
def main():
    for i in range (5):
    #Let the user use the menu up to 5 times at a time
        choice = menu()
        action(choice)
main()