#!/usr/bin/env python3

#Script Name: bruteforce_suit
#Purpose: Brute force SSH and Zip files
#Example usage: Crack codes
#Expected output: Access through SSH - Access to Zip content

### needs a lot of work, sorry got caught fixing some details on the lab

import logging

log = logging.getLogger(__name__)

def do_something():
    log.debug("Doing something!")
    
   import logging
import os

logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))

exit(main())
Try to incorporate logging capabilities into your Python tools.
