#!/usr/bin/env python3

#Script Name: encryption
#Purpose: Encrypt of data
#Example usage: protect the integrity of data
#Expected output: encrypted data
#variables:

###stil in progress####

from cryptography.fernet import Fernet

def gen():
    key = Fernet.generate_key()
    # Generates key
    with open("master", "wb") as key_file:
        key_file.write(key)

def load():
    # Loads the key from directory 'master'
    return open("key.key", "rb").read()

def menu():
    print("1) Encrypt File")
    print("2) Decrypt File")
    print("3) Encrypt phrase")
    print("4) Decrypt phrase")
    print("5) Quit\n")

gen()
# Generates new key
***********

# load the previously generated key
key = load()
print("Key is "+str(key.decode('utf-8')))

message = "hello friend".encode()
print("Plaintext is "+str(message.decode('utf-8')))

# Initialize the Fernet class
f = Fernet(key)

# Encrypt the message
encrypted = f.encrypt(message)

# Print how it looks
print("Ciphertext is "+encrypted.decode('utf-8'))

#####
# value of key is assigned to a variable
f = Fernet(key)
  
# the plaintext is converted to ciphertext
token = f.encrypt(b"welcome to geeksforgeeks")
  
# display the ciphertext
print(token)
