#!/usr/bin/env python3

#Script Name: bruteforce_suit
#Purpose: Brute force SSH and Zip files
#Example usage: Crack codes
#Expected output: Access through SSH - Access to Zip content

#!/usr/bin/env python3

#Script Name: bruteforce_suit
#Purpose: Brute force SSH and Zip files
#Example usage: Crack codes
#Expected output: Access through SSH - Access to Zip content

import os

print ("\nHi, I'm going to help you find your file")
file = input("\nPlease give the name of the file to look for: ")
directory = input ("Also a directory that contains the file at some level: ")
ostype = input ("Great! Are we working on Linux or Windows? ")
choice = ostype.lower() 

#Looks for matches, enumerate them and provide the number of searches for Linux
def linux():
    os.system("find " + directory + " -name " + file + "|echo \"\nNumber of matches found: $(grep -c /)\"")
    #Find matches and count them
    os.system("find " + directory + " -name " + file)
    #Puths path together
    os.system("ls " + directory + "|echo \"Number of counted files: $(wc -l)\"")
    #List elements inside the directory and counts them

#For Windows
def win():
    matches = os.popen("dir /b/s " + directory + "\\" + file + "| find /c \":\\\"").read()
    #Find matches and count them
    print(f"\nNumber of matches found: {matches}")
    os.system("dir /b/s " + directory + "\\" + file)
    #Puths path together
    count = os.popen("dir /s /b " + directory + "| find /c \":\\\"").read()
    #List elements inside the directory and counts them
    print(f"Number of counted files: {count}")

if choice == "linux":
    linux()
elif choice == "windows":
    win()
else:
    print ("Invalid option") 
