#!/usr/bin/python3

import socket

sockmod = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
timeout = 
sockmod.settimeout(timeout)

hostip = 
portno = 

def portScanner(portno):
    if sockmod.FUNCTION((hostip, portno)): 
        print("Port closed")
    else:
        print("Port open")

portScanner(port)
