#!/usr/bin/env python3

#Script Name: port_scanner
#Purpose: Check to see if a port is open
#Example usage: Look for open ports to exploit
#Expected output: Open or close response

import socket

#Creates a socket in the family AF_INETand type SOCK_STREAM.
#they are both default options. 
sockmod = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
#How many seconds to wait for the response, before timing out.
timeout = 5
sockmod.settimeout(timeout)

#Ask user for target's IP
host_ip = input("Please provide the target's IP: ")
#Ask user for port to scan
port_number = int(input("Please provide port number to scan: "))

#Scans for the port given in the IP provided
def portScanner(port_number):
    #Determine if the port is closed or not
    if sockmod.connect((host_ip, port_number)):
        print("Port closed")
    else:
        print("Port open")

portScanner(port_number)
