#!/usr/bin/env python3

#Script Name: xss_detector
#Purpose: Test URLs for XSS vulnerabilities
#Example usage: Evaluate URL vulnerability for XSS
#Expected output: Evaluation of URL with forms being detected

### TODO: Install bs4 

import requests
from pprint import pprint
from bs4 import BeautifulSoup as bs
from urllib.parse import urljoin

#Returns all forms from the HTML content
def get_all_forms(url):
    #Request of the URL content is parse with "html parser" using
    #beautiful soup and place it on a variable
    soup = bs(requests.get(url).content, "html.parser")
    #Returns the information matching "form"
    return soup.find_all("form")

#Extract atributes and details from forms
def get_form_details(form):
    #Opens set of key/values for mapping
    details = {}
    #Gets the atributes in the form "action" (URL)
    action = form.attrs.get("action").lower()
    #From the form "method" (POST, GET, etc)
    method = form.attrs.get("method", "get").lower()
    #Opens a list
    inputs = []
    #Gets all the input information and goes through it to classify it
    for input_tag in form.find_all("input"):
        input_type = input_tag.attrs.get("type", "text")
        input_name = input_tag.attrs.get("name")
        #Appends the information parsed into "type" and "name"
        inputs.append({"type": input_type, "name": input_name})
    #Sends these types into the list, for a dictionary reference
    details["action"] = action
    details["method"] = method
    details["inputs"] = inputs
    return details

#Submits a form given by "form_details", takes the form's URL,
#value will take the form of search inputs 
def submit_form(form_details, url, value):
    #Puts together a full absolute URL based on the "action" list
    target_url = urljoin(url, form_details["action"])
    inputs = form_details["inputs"]
    data = {}
    
    for input in inputs:
        #Given input in the form of "text" or "search" is taken as "value"
        if input["type"] == "text" or input["type"] == "search":
            input["value"] = value
        input_name = input.get("name")
        input_value = input.get("value")
        #When "input_name" and "input_value" have a value different to
        #zero, they are added to "data" list for submission
        if input_name and input_value:
            data[input_name] = input_value
    
    #Submits a post or get request depending on the form method
    if form_details["method"] == "post":
        return requests.post(target_url, data=data)
    else:
        return requests.get(target_url, params=data)
